### ISSUE TITLE
Globe is not view able at mobile device

### ISSUE THREAD

**Issue by sharif2008** [sorxrob/covid3d#2]
Hi, Thanks for your amazing project.

The project is working for desktop. But globe/world map is not viewable at mobile. Am I missing something ?  What to do next?

**Comment by sorxrob** [comment]
Hi, which browser are you using?

**Comment by sharif2008** [comment]
I tried safari and chrome . But your website works fine in the same browser....

**Comment by sorxrob** [comment]
You are running your own app or your viewing covid3d.live from your mobile phone?

**Comment by sharif2008** [comment]
I am viewing your app from my which is fine. But my app deployed locally, globe is not shown . Let me upload my build in some server.

**Comment by sharif2008** [comment]
can you please check this from your mobile? http://topheadlines24.com/covid3d/

**Comment by sorxrob** [comment]
Your url works on my mobile (OnePlus 7 pro)

**Comment by sharif2008** [comment]
My one is iPhone 6s ? Can you check in any iPhone? It did not work in my friends iPhone too....

**Comment by sorxrob** [comment]
I'll check
