### ISSUE TITLE
wrong country name and data 2

### ISSUE THREAD

**Issue by hentaicracker** [sorxrob/covid3d#4]
![image](https://user-images.githubusercontent.com/11981606/78338045-9f027680-75c4-11ea-8f40-8332e42b1f67.png)
Taiwan is part of China =>
https://en.wikipedia.org/wiki/Taiwan,_China

In addition,

Covid-19 did not originate in China, stop positioning the map in China at the beginning.

**Comment by sorxrob** [comment]
It's not positioned in China. It gets your coordinates and zoom in there.

**Comment by sorxrob** [comment]
Hi Jason,

First of all thanks for pointing that out. Second, it's not positioned in China. It gets the coordinates using the IP address of the request and centers it there.

Please feel free to check the code before leaving an issue. Thanks.

**Comment by sorxrob** [comment]
![Screen Shot 2020-05-01 at 9 32 12 AM](https://user-images.githubusercontent.com/13049130/80774113-a5b5e680-8b8e-11ea-895e-d4d2c393689a.png)
